// export const supabaseUrl = 'https://tysqlbunmnyrwlltlgra.supabase.co'

// export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5c3FsYnVubW55cndsbHRsZ3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NjU3NTQsImV4cCI6MjA1MjM0MTc1NH0.yCuELbvXrJIHGx9j6sNm8Or3uh1fYgFZ4VHtt9G56RA'

// OLD DB
export const supabaseUrl = 'https://meytxpdgqdknwejkepbe.supabase.co'

export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1leXR4cGRncWRrbndlamtlcGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNTI5MTMsImV4cCI6MjA1MTkyODkxM30.pFd7aLSP-kGNzOyM1FdgPlBaXz2tXSGQSu0DUi5I0dw'

