export const supabaseUrl = 'https://meytxpdgqdknwejkepbe.supabase.co'

export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1leXR4cGRncWRrbndlamtlcGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNTI5MTMsImV4cCI6MjA1MTkyODkxM30.pFd7aLSP-kGNzOyM1FdgPlBaXz2tXSGQSu0DUi5I0dw'

